//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cage
    {
        public int cage_id { get; set; }
        public Nullable<int> animal_id { get; set; }
    
        public virtual Animal Animal { get; set; }
    }
}
