//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8.DBConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class circusEntities : DbContext
    {
        public circusEntities()
            : base("name=circusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Artist> Artist { get; set; }
        public virtual DbSet<Cage> Cage { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<HoloRoom> HoloRoom { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Responsible> Responsible { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trainer> Trainer { get; set; }
        public virtual DbSet<Training> Training { get; set; }
        public virtual DbSet<TrainingParticipant> TrainingParticipant { get; set; }
    }
}
