//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsible
    {
        public int responsible_id { get; set; }
        public string name { get; set; }
        public Nullable<int> room_id { get; set; }
    
        public virtual HoloRoom HoloRoom { get; set; }
    }
}
